name: GitHub Actions Build and Deploy icodemini
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: peaceiris/actions-gh-pages@v3
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: ./dist
        BUILD_SCRIPT: npm install && npm run docs:build
